kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: isiak-workload
networking:
    podSubnet: "10.246.0.0/16"
    serviceSubnet: "10.98.0.0/16"
nodes:
    - role: control-plane
    - role: worker

